### ISSUE TITLE
Question of how to obtain "reaxys_test_full_nice_classes.csv"?

### ISSUE THREAD

**Issue by GWwangshuo** [Academich/reagents#3]
Thanks for your nice work. We are currently following this work and trying to reimplement some of your experimental results. Since Reaxys data is not allowed to be publicly shared, could you please share with us the reaction ids which comprise your test dataset? That will be greatly helpful. Thanks a lot.

**Comment by Academich** [comment]
Sure! Reaction IDs are provided in the file "reaction_ids_reaxys.txt" together with trained models at https://drive.google.com/drive/folders/1weP5wG_wzd9qb3RVnCz0JjyB-TJF-5yQ
